version: '3'
services:
  redis:
    image: 'redis:alpine'
  autobuilder:
    image: 'tedkulp/docker-autobuilder:latest'
    ports:
      - 3004:3000
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./config/config.yaml:/app/config/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
